<?xml version="1.0"?>
<package format="3">
  <name>tf_package_reference</name>
  <version>0.0.0</version>
  <description>CS 354 reference showing relative topics and namespaced TF.</description>
  <maintainer email="molloykp@jmu.edu">molloykp</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
